In [3]:
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

In [4]:
DATASET_DIR = '/cluster/tufts/c26sp1cs0137/data/assignment2_data/dataset'

In [5]:
targets = torch.load(f'{DATASET_DIR}/targets.pt', weights_only=False)

for key in targets.keys():
    print("---------------------------------------------------------------------------")
    print(key)
    print(targets[key])

---------------------------------------------------------------------------
time
['2018-07-13T00:00:00.000000000' '2018-07-13T01:00:00.000000000'
 '2018-07-13T02:00:00.000000000' ... '2021-07-11T21:00:00.000000000'
 '2021-07-11T22:00:00.000000000' '2021-07-11T23:00:00.000000000']
---------------------------------------------------------------------------
variable_names
['TMP@2m_above_ground', 'RH@2m_above_ground', 'UGRD@10m_above_ground', 'VGRD@10m_above_ground', 'GUST@surface', 'APCP_1hr_acc_fcst@surface']
---------------------------------------------------------------------------
values
tensor([[ 2.9425e+02,  5.6812e+01, -2.2344e+00,  1.0342e+00,  5.8047e+00,
          0.0000e+00],
        [ 2.9275e+02,  6.5188e+01, -5.9424e-01,  3.4644e-01,  5.4688e+00,
          0.0000e+00],
        [ 2.9175e+02,  7.0188e+01, -1.5247e-01, -1.0028e-01,  3.9727e+00,
          0.0000e+00],
        ...,
        [ 2.9950e+02,  6.2312e+01,  9.4189e-01,  3.3594e+00,  5.5039e+00,
          0.0000e+00],
   

In [6]:
len(targets["values"])

26280

In [ ]:
input1 = torch.load(f'{DATASET_DIR}/inputs/2018/X_2018071300.pt', weights_only=False)



tensor([ 2.9800e+02,  5.6750e+01,  1.4893e-02, -1.7812e+00,  3.1875e+00,
         9.1500e+01,  0.0000e+00,  0.0000e+00,  2.8800e+02,  2.5300e+02,
         2.4700e+02,  2.7800e+02,  2.8400e+02,  1.7500e+02,  5.9200e+03,
         3.2000e+03,  1.5840e+03,  2.4400e+02,  3.0000e+02,  2.6800e+02,
         2.8200e+02,  2.8800e+02,  2.9400e+02, -3.1055e-01,  8.7500e+00,
         6.3750e+00, -2.9102e-01, -1.5000e+00, -1.5469e+00, -1.6016e+00,
        -1.3000e+01, -8.8125e+00, -2.6719e+00,  4.0430e-01, -3.1562e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  1.9250e+01,
         2.9125e+01,  0.0000e+00], dtype=torch.bfloat16)
tensor([ 3.0000e+02,  5.1750e+01, -1.1035e-01, -1.7188e+00,  3.0625e+00,
         9.1000e+01,  0.0000e+00,  0.0000e+00,  2.8800e+02,  2.5300e+02,
         2.4600e+02,  2.7800e+02,  2.8400e+02,  1.7500e+02,  5.9200e+03,
         3.2000e+03,  1.5840e+03,  2.4400e+02,  3.0000e+02,  2.6800e+02,
         2.8200e+02,  2.8800e+02,  2.9400e+02, -3.1055e-01,  8.8125

Layer Type,Typical Input Shape,Typical Output Shape,What happens?
Convolution,"(B, 42, 450, 449)","(B, 64, 450, 449)","The ""Channels"" increase (depth), while spatial size stays similar."
MaxPool,"(B, 64, 450, 449)","(B, 64, 225, 224)",The spatial size is cut in half (Height/Width shrink).
Linear (FC),"(B, Flattened_Vector)","(B, 6)","The spatial maps are ""squashed"" into your 6 final target numbers."